config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :home, only: :index

  resources :projects
  resources :tasks, except: :update do
    collection do
      put :update
    end
    member do
      post :resume
    end
  end

  root 'home#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  scope :default, -> { order(created_at: :desc) }
  scope :tasks_without_project, -> { includes(:tasks).where('tasks.project_id is null') }

  validates :time, presence: true, on: :update

  before_save :set_date
  before_save :set_time
  before_create :set_from_time
  before_update :set_to_time

  private

  def set_date
    if date_done.blank?
      self.date_done = Date.today
    end
  end

  def set_time
    if from_time && to_time
      elapsed = self.to_time - self.from_time
      self.time = Time.at(elapsed).utc
    end
  end

  def set_from_time
    if from_time.blank?
      self.from_time = Time.now
    end
  end

  def set_to_time
    if self.to_time.blank?
      self.to_time = Time.now
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :tasks

  validates :provider, presence: true

  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      name: auth_hash.info.nickname,
      profile_image: auth_hash.info.image,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret,
      nickname: auth_hash.info.nickname
    )
    user
  end

  def tasks_without_project
    tasks.where('project_id is null')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to root_path if current_user.blank?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    redirect_to projects_path if current_user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @task = Task.new
    @tasks = current_user.tasks_without_project.decorate
    @projects = current_user.projects.includes(:tasks).decorate
  end

  def new
    @project = current_user.projects.build
    respond_to :js
  end

  def create
    @project = current_user.projects.new(project_params)

    flash[:success] = 'Project created' if @project.save
    @project = @project.decorate

    respond_to :js
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:success] = 'Project Deleted'

    respond_to :js
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, except: :destroy

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    flash[:success] = 'Welcome to TimeTracking'
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = "Sucessfully logged out!"
    end
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :build_task, only: [:new, :create]

  def edit
    @task = Task.find(params[:id])
    @projects = current_user.projects

    @task = @task.decorate

    respond_to :js
  end

  def create
    @task.attributes = task_params

    @task = @task.decorate if @task.save

    flash[:success] = 'Task created'

    respond_to :js
  end

  def update
    @task = Task.find(task_params[:id])

    @task.update_attributes(task_params)

    @task = @task.decorate

    respond_to :js
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    flash[:success] = 'Task Deleted'

    respond_to :js
  end

  def resume
    @task = Task.find(params[:id])

    @task = @task.dup

    @task.time = nil
    @task.from_time = nil
    @task.to_time = nil

    @task.save

    render json: { task_id: @task.id }
  end

  private

  def build_task
    project_id = params[:project_id] || params.dig(:task, :project_id)

    @task = if project_id.present?
              project = Project.find(project_id)
              project.tasks.build
            else
              current_user.tasks.new
            end
  end

  def task_params
    params.require(:task).permit(:id, :name, :date_done, :from_time, :to_time, :time, :description, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<div class='container'>
  <div class="jumbotron .container-fluid">
    <h1 class="display-3">TimeTracking System</h1>
    <p class="lead">Welcome to the time tracking app.</p>
    <hr class="my-4">
    <p>To start using it log in with your twitter account.</p>
    <p class="lead">
      <%= link_to "/auth/twitter" do %>
        <%= image_tag 'https://g.twimg.com/dev/sites/default/files/images_documentation/sign-in-with-twitter-gray.png' %>
      <% end %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrackingTime</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='header'>
    <%= render partial: 'shared/header' %>
  </div>
  <div id='flash'>
    <%= render partial: 'shared/flash_messages' %>
  </div>
  <%= yield %>
</body>
</html>

app/views/projects/_new.html.erb
<div class="modal" id='new_project_modal'>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Project</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for project, remote: :true, html: { id: 'js-new-project-form' } do |f| %>
          <div class='form-group'>
            <%= f.label :name %>
            <%= f.text_field :name, placeholder: 'Project Name', class: 'form-control' %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary js-create-project">Create</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/projects/_no_project.html.erb
<div class="card">
  <div class="card-header" role="tab" id="tasks_without_project_header">
    <h5 class="mb-0">
      <a data-toggle="collapse" href="#no_project" aria-expanded="false" aria-controls="no_project">
        Tasks without project <span class="badge badge-pill badge-secondary js-no-project-task-count"><%= tasks.count %></span>
      </a>
    </h5>
  </div>

  <div id="no_project" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
    <div class="card-body">
      <table class='table'>
        <thead>
          <th>Project</th>
          <th>Name</th>
          <th>Description</th>
          <th>Time Spent</th>
          <th>From - To</th>
          <th>Date</th>
          <th></th>
        </thead>
        <tbody id='tasks_without_project'>
          <%= render partial: 'tasks/task', collection: tasks %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/projects/_project.html.erb
<div class="card" id="project_card_<%= project.id %>">
  <div class="card-header" role="tab" id="project_header_<%= project.id %>">
    <h5 class="mb-0">
      <a data-toggle="collapse" href="#project_tasks_<%= project.id %>" aria-expanded="false" aria-controls="project_tasks_<%= project.id %>">
        <%= project.name %>
      </a>
      <span class="badge badge-pill badge-secondary js-project-task-count"><%= project.tasks_count %></span>
      <%= link_to 'New Task', 'javascript://', class: 'btn btn-secondary js-new-task', 'data-project-id' => project.id %>
      <%= link_to project_path(project), class: 'btn btn-secondary', method: :delete, remote: :true, 'data-confirm' => "Are you sure you want to delete project #{ project.name }?" do %>
        <span class='oi oi-trash'></span>
      <% end %>
    </h5>
  </div>

  <div id="project_tasks_<%= project.id %>" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
    <div class="card-body">
      <table class='table'>
        <thead>
          <th>Project</th>
          <th>Name</th>
          <th>Description</th>
          <th>Time Spent</th>
          <th>From - To</th>
          <th>Date</th>
          <th></th>
        </thead>
        <tbody id="project_<%= project.id %>">
          <%= render partial: 'tasks/task', collection: project.tasks %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/projects/create.js.erb
<%- if !@project.valid? %>
  $('#js-new-project-form').render_form_errors('project', <%= raw @project.errors.to_json %>)
<% else %>
  $('#new_project_modal').modal('hide');
  $('#projects_accordion').append("<%= j render partial: 'project', locals: { project: @project } %>");
  $('#task_project_id').append('<option value="<%= @project.id %>" ><%= @project.name %></option>')
  $('#flash').html('<%= j render partial: "shared/flash_messages" %>');
<% end %>

app/views/projects/destroy.js.erb
var id = "<%= @project.id %>";
$('#project_card_' + id).remove();
$('#flash').html('<%= j render partial: "shared/flash_messages" %>');

app/views/projects/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-12 mb-1">
      <h1>Projects</h1>
    </div>
  </div>
  <div class='row'>
    <div class="col-12 mb-2">
      <%= link_to 'New Project', new_project_path, class: 'btn btn-primary', remote: :true %>
    </div>
  </div>
  <div class='row'>
    <div class='col'>Click on timer to set a date, start hour and end hour</div>
    <div class="col-12 mb-2">
      <%= render partial: 'tasks/new_task', locals: { task: @task, projects: @projects } %>
    </div>
  </div>
  <div class='row'>
    <div id="projects_accordion" class='col-12' role="tablist">
      <%= render partial: 'no_project', locals: { tasks: @tasks } %>
      <%= render @projects %>
    </div>
  </div>
</div>
<div id='new_project_modal'></div>
<div id='edit_task_modal'></div>

app/views/projects/new.js.erb
$('#new_project_modal').replaceWith("<%= j render partial: 'new', locals: { project: @project } %>");
$('#new_project_modal').modal('show');

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= value %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<ul class='nav justify-content-end'>
  <% if current_user %>
    <li class='nav-item'>
      <%= image_tag current_user.profile_image, class: 'rounded-circle' %>
      <%= current_user.name %>
    </li>
    <li class='nav-item'>
      <%= link_to 'Log Out', logout_path, method: :delete %>
    </li>
  <% end %>
</ul>

app/views/tasks/_edit.html.erb
<div class="modal" id='edit_task_modal'>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for task, url: tasks_path, remote: :true, method: :put, html: { id: 'js-edit-task-form' } do |f| %>
          <div class='form-row'>
            <%= f.hidden_field :id %>
            <div class='form-group'>
              <%= f.label :description %>
              <%= f.text_field :description, placeholder: 'Description', class: 'form-control' %>
            </div>
            <div class='form-group'>
              <%= f.label :name %>
              <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary js-update-task">Update</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_new_task.html.erb
<div class='d-inline-block'>
  <%= form_for task, remote: true, html: { id: 'new_task' } do |f| %>
    <div class='form-row'>
      <div class="col-3">
        <%= f.text_field :description, placeholder: 'Description', class: 'form-control' %>
      </div>
      <div class="col-3">
        <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>
      </div>
      <div class="col">
        <%= f.select :project_id, options_for_select(projects.map { |project| [project.name, project.id] }), { prompt: '' }, { class: 'form-control' } %>
      </div>
      <div id='task_done_from_to' style='display: none;'>
        <div class="col">
          <%= f.text_field :date_done, placeholder: 'Date', class: 'form-control datepicker' %>
        </div>
        <div class="col">
          <%= f.hidden_field :time %>
          <%= f.text_field :from_time, placeholder: 'From', class: 'form-control time-from' %>
          <%= f.text_field :to_time, placeholder: 'To', class: 'form-control time-to' %>
        </div>
      </div>
      <div class="col">
        <h4 id='elapsed_time'>00:00:00</h4>
      </div>
    </div>
  <% end %>
</div>

<div class='d-inline-block float-xs-right'>
  <%= button_tag class: 'btn btn-success js-start-timer' do %>
    <span class="oi oi-media-play"></span>
  <% end %>
  <%= button_tag class: 'btn btn-danger js-stop-timer', style: 'display: none' do %>
    <span class="oi oi-media-stop"></span>
  <% end %>
</div>

<div>
  <%= form_for task, remote: true, method: :put, html: { class: 'js-stop-form' , id: 'update_task'} do |f| %>
    <div class='form-row'>
      <%= f.hidden_field :id %>
      <%= f.hidden_field :time %>
    </div>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<tr id="task_<%= task.id %>">
  <td><%= task.project_name %></td>
  <td><%= task.name %></td>
  <td><%= task.description %></td>
  <td><%= task.elapsed_time %></td>
  <td><%= task.from_to %></td>
  <td><%= task.date_done %></td>
  <td>
    <%= link_to 'edit', edit_task_path(task), remote: true, class: 'js-task-edit' %>
    <%= link_to task_path(task), method: :delete, remote: true, 'data-confirm' => "Are you sure you want to delete task #{ task.name }?" do %>
      <span class='oi oi-trash'></span>
    <% end %>
    <%= link_to 'javascript://', class: 'js-task-resume', 'data-task-id' => task.id, 'data-time' => task.time do %>
      <span class="oi oi-media-play"></span>
    <% end %>
  </td>
</tr>

app/views/tasks/create.js.erb
var task_id = "<%= @task.id %>";

$('#task_id').val(task_id);

<%- if !@task.to_time.present? %>
  $('.js-start-timer').hide();
  $('.js-stop-timer').show();
<% else %>
  <%- if @task.project_id %>
    var project_id = "<%= @task.project_id %>";
    $('#project_' + project_id).prepend("<%= j render partial: 'tasks/task', locals: { task: @task } %>");
    var task_count = Number($('#project_header_' + project_id + ' .js-project-task-count').text());
    $('#project_header_' + project_id + ' .js-project-task-count').text(task_count + 1);
  <% else %>
    $('#tasks_without_project').prepend("<%= j render partial: 'tasks/task', locals: { task: @task } %>");
    var task_count = Number($('#tasks_without_project_header .js-no-project-task-count').text());
    $('#tasks_without_project_header .js-no-project-task-count').text(task_count + 1);
  <% end %>
  $('#flash').html('<%= j render partial: "shared/flash_messages" %>');
  $('input[type="text"],select').val('');
<% end %>

app/views/tasks/destroy.js.erb
var id = "<%= @task.id %>";
$('#task_' + id).remove();

<%- if @task.project_id %>
  var project_id = "<%= @task.project_id %>";
  var task_count = Number($('#project_header_' + project_id + ' .js-project-task-count').text());
  $('#project_header_' + project_id + ' .js-project-task-count').text(task_count - 1);
<% else %>
  var task_count = Number($('#tasks_without_project_header .js-no-project-task-count').text());
  $('#tasks_without_project_header .js-no-project-task-count').text(task_count - 1);
<% end %>

$('#flash').html('<%= j render partial: "shared/flash_messages" %>');

app/views/tasks/edit.js.erb
$('#edit_task_modal').replaceWith("<%= j render partial: 'edit', locals: { task: @task } %>");
$('#edit_task_modal').modal('show');

app/views/tasks/update.js.erb
$('.js-start-timer').show();
$('.js-stop-timer').hide();

var task_id = "<%= @task.id %>"

if($('#task_' + task_id).length > 0){
  $('#task_' + task_id).replaceWith("<%= j render partial: 'tasks/task', locals: { task: @task } %>");
} else{
  <%- if @task.project_id %>
    var project_id = "<%= @task.project_id %>";
    $('#project_' + project_id).prepend("<%= j render partial: 'tasks/task', locals: { task: @task } %>");
    var task_count = Number($('#project_header_' + project_id + ' .js-project-task-count').text());
    $('#project_header_' + project_id + ' .js-project-task-count').text(task_count + 1);
  <% else %>
    $('#tasks_without_project').prepend("<%= j render partial: 'tasks/task', locals: { task: @task } %>");
    var task_count = Number($('#tasks_without_project_header .js-no-project-task-count').text());
    $('#tasks_without_project_header .js-no-project-task-count').text(task_count + 1);
  <% end %>
}

$('#flash').html('<%= j render partial: "shared/flash_messages" %>');

$('input[type="text"],select').val('');
$('#edit_task_modal').modal('hide');